<?php

declare(strict_types=1);

namespace Bellcom\StarsTurnBundle\Domain;

use Bellcom\StarsTurnBundle\Entity\Turn;

final class DemoTurnEngine implements TurnEngineInterface
{
    public function generate(Turn $turn, array $submittedOrders): TurnGenerationResult
    {
        $state = TechnologyModelCatalog::normalizeState($turn->getInitialState());
        $currentYear = (int) ($state['year'] ?? 2400);

        ksort($submittedOrders, SORT_STRING);

        $nextState = $state;
        $nextState['year'] = $currentYear + 1;
        $nextState['last_turn'] = $turn->getNumber();
        $nextState['rules_version'] = $turn->getRulesVersion();
        $nextState['seed'] = $turn->getRandomSeed();
        $nextState['submitted_orders'] = $submittedOrders;

        $systems = is_array($nextState['universe']['systems'] ?? null)
            ? $nextState['universe']['systems']
            : [];
        $routes = is_array($nextState['universe']['routes'] ?? null)
            ? $nextState['universe']['routes']
            : [];
        $fleets = is_array($nextState['universe']['fleets'] ?? null)
            ? $nextState['universe']['fleets']
            : [];
        $researchByPlayer = is_array($nextState['research'] ?? null)
            ? $nextState['research']
            : [];

        $systemIds = [];
        $startingOwners = [];
        foreach ($systems as $index => $system) {
            if (is_array($system) && is_string($system['id'] ?? null)) {
                $systemId = (string) $system['id'];
                $systemIds[$systemId] = $index;
                $startingOwners[$systemId] = isset($system['ownerPlayerId']) && is_numeric($system['ownerPlayerId'])
                    ? (int) $system['ownerPlayerId']
                    : null;
            }
        }

        // Colonies receive the income generated by their actually installed
        // extraction infrastructure and local natural potential. Keep a compact
        // per-colony breakdown for the owner's turn report.
        $resourceIncomeByPlayer = [];
        foreach ($systems as $index => $system) {
            if (!is_array($system) || ($system['ownerPlayerId'] ?? null) === null) {
                continue;
            }

            $resources = is_array($system['resources'] ?? null) ? $system['resources'] : [];
            $incomeByResource = [];
            foreach ($resources as $resourceIndex => $resource) {
                if (!is_array($resource)) {
                    continue;
                }
                $resourceId = is_string($resource['id'] ?? null) ? (string) $resource['id'] : '';
                $income = max(0, (int) ($resource['income'] ?? 0));
                $resources[$resourceIndex]['value'] = max(0, (int) ($resource['value'] ?? 0)) + $income;
                if ($resourceId !== '') {
                    $incomeByResource[$resourceId] = $income;
                }
            }
            $systems[$index]['resources'] = array_values($resources);
            $ownerId = (int) $system['ownerPlayerId'];
            $resourceIncomeByPlayer[$ownerId][] = [
                'systemId' => (string) ($system['id'] ?? ''),
                'systemName' => (string) ($system['name'] ?? $system['id'] ?? 'Colony'),
                'income' => $incomeByResource,
                'potential' => is_array($system['resourcePotential'] ?? null) ? $system['resourcePotential'] : [],
                'output' => is_array($system['resourceOutput'] ?? null) ? $system['resourceOutput'] : [],
                'asteroids' => is_array($system['asteroids'] ?? null) ? $system['asteroids'] : null,
            ];
        }

        // Existing installation upgrades advance after this turn's income has been
        // collected. A factory that completes now therefore improves income starting
        // next turn; the old model remained active for the whole work period.
        $upgradeCompletionsByPlayer = [];
        $upgradeWarningsByPlayer = [];
        foreach ($systems as $index => $system) {
            if (!is_array($system) || !isset($system['ownerPlayerId']) || !is_numeric($system['ownerPlayerId'])) {
                continue;
            }
            $ownerId = (int) $system['ownerPlayerId'];
            $advanced = TechnologyModelCatalog::advanceInstallationUpgrades($system, $turn->getNumber() + 1);
            $systems[$index] = $advanced['system'];
            if ($advanced['completed'] !== []) {
                $upgradeCompletionsByPlayer[$ownerId] = array_merge($upgradeCompletionsByPlayer[$ownerId] ?? [], $advanced['completed']);
            }
            foreach ($advanced['warnings'] as $warning) {
                $upgradeWarningsByPlayer[$ownerId][] = sprintf('%s: %s', (string) ($system['name'] ?? $system['id'] ?? 'Colony'), $warning);
            }
        }

        // Fleet refits already in progress advance before this turn's new fleet
        // orders are resolved. Hardware remains unchanged until the refit completes.
        $refitCompletionsByPlayer = [];
        $refitWarningsByPlayer = [];
        foreach ($fleets as $fleetIndex => $fleet) {
            if (!is_array($fleet) || !isset($fleet['ownerPlayerId']) || !is_numeric($fleet['ownerPlayerId'])) {
                continue;
            }
            $ownerId = (int) $fleet['ownerPlayerId'];
            $advanced = $this->advanceFleetRefit($fleet, $state, $turn->getNumber() + 1);
            $fleets[$fleetIndex] = $advanced['fleet'];
            if ($advanced['completed'] !== null) {
                $refitCompletionsByPlayer[$ownerId][] = $advanced['completed'];
            }
            if ($advanced['warning'] !== null) {
                $refitWarningsByPlayer[$ownerId][] = $advanced['warning'];
            }
        }

        // Fleets automatically refuel before orders are resolved when they start
        // the processing cycle at one of their owner's colonies. This lets a fleet
        // arrive low on fuel one turn, then depart full on the following turn.
        $fuelRefillsByPlayer = [];
        foreach ($fleets as $fleetIndex => $fleet) {
            if (!is_array($fleet) || !isset($fleet['ownerPlayerId']) || !is_numeric($fleet['ownerPlayerId'])) {
                continue;
            }
            $ownerId = (int) $fleet['ownerPlayerId'];
            $normalized = TechnologyModelCatalog::normalizeFleet($fleet, $state);
            $systemId = is_string($normalized['systemId'] ?? null) ? $normalized['systemId'] : '';
            $capacity = max(0, (int) ($normalized['fuelCapacity'] ?? 0));
            $before = max(0, min($capacity, (int) ($normalized['fuel'] ?? $capacity)));

            if ($systemId !== '' && ($startingOwners[$systemId] ?? null) === $ownerId && $before < $capacity) {
                $normalized['fuel'] = $capacity;
                $normalized = TechnologyModelCatalog::normalizeFleet($normalized, $state);
                $fuelRefillsByPlayer[$ownerId][] = [
                    'fleetId' => (string) ($normalized['id'] ?? ''),
                    'fleetName' => (string) ($normalized['name'] ?? $normalized['id'] ?? 'Fleet'),
                    'systemId' => $systemId,
                    'fuelBefore' => $before,
                    'fuelAfter' => $capacity,
                    'fuelAdded' => $capacity - $before,
                    'fuelCapacity' => $capacity,
                ];
            }
            $fleets[$fleetIndex] = $normalized;
        }

        $reports = [];
        foreach ($submittedOrders as $playerId => $orders) {
            $playerIdInt = (int) $playerId;
            $movements = [];
            $colonizations = [];
            $productions = [];
            $fleetActions = [];
            $refitsStarted = [];
            $refitsCompleted = $refitCompletionsByPlayer[$playerIdInt] ?? [];
            $fuelRefills = $fuelRefillsByPlayer[$playerIdInt] ?? [];
            $resourceIncome = $resourceIncomeByPlayer[$playerIdInt] ?? [];
            $installationUpgradesCompleted = $upgradeCompletionsByPlayer[$playerIdInt] ?? [];
            $designsCreated = [];
            $researchCompleted = [];
            $researchProgress = null;
            $warnings = array_merge(
                $upgradeWarningsByPlayer[$playerIdInt] ?? [],
                $refitWarningsByPlayer[$playerIdInt] ?? [],
            );
            $movedFleetIds = [];
            $managedFleetIds = [];
            $fleetManagementSequence = 0;
            $playerResearch = ResearchCatalog::playerState(['research' => $researchByPlayer], $playerIdInt);
            $researchIncome = ResearchCatalog::estimateIncome($state, $playerIdInt);
            $fleetOrders = is_array($orders['fleets'] ?? null) ? array_values($orders['fleets']) : [];

            // Ship generations are explicit design orders. Research only unlocks
            // component models; a completed technology never mutates or silently
            // replaces an existing design. New designs become available next turn.
            $designOrders = is_array($orders['designs'] ?? null) ? array_values($orders['designs']) : [];
            foreach ($designOrders as $designOrder) {
                if (!is_array($designOrder)) {
                    continue;
                }
                $baseDesignId = is_string($designOrder['baseDesignId'] ?? null) ? trim($designOrder['baseDesignId']) : '';
                $name = is_string($designOrder['name'] ?? null) ? trim($designOrder['name']) : '';
                $componentModelIds = is_array($designOrder['componentModelIds'] ?? null) ? $designOrder['componentModelIds'] : [];
                try {
                    $design = TechnologyModelCatalog::createDesign($nextState, $playerIdInt, $baseDesignId, $name, $componentModelIds);
                    $expectedId = is_string($designOrder['designId'] ?? null) ? $designOrder['designId'] : '';
                    if ($expectedId !== '' && $expectedId !== (string) $design['id']) {
                        $warnings[] = sprintf('Design order %s changed while the turn was waiting and was not created.', $name !== '' ? $name : $expectedId);
                        continue;
                    }
                    $nextState = TechnologyModelCatalog::appendDesign($nextState, $playerIdInt, $design, $turn->getNumber() + 1);
                    $designsCreated[] = [
                        'designId' => (string) $design['id'],
                        'name' => (string) $design['name'],
                        'family' => (string) $design['family'],
                        'generation' => (int) $design['generation'],
                        'basedOnDesignId' => $design['basedOnDesignId'] ?? null,
                        'components' => $design['components'] ?? [],
                        'stats' => $design['stats'] ?? [],
                        'industryCost' => (int) ($design['industryCost'] ?? 0),
                    ];
                } catch (\InvalidArgumentException $exception) {
                    $warnings[] = sprintf('Ship design %s could not be created: %s', $name !== '' ? $name : 'unnamed', $exception->getMessage());
                }
            }

            // Fleet organization is explicit turn state. Split/transfer/merge and
            // refit happen before movement. A fleet involved in structural work this
            // turn cannot also move or colonize; rename is the only harmless exception.
            foreach ($fleetOrders as $fleetOrder) {
                if (!is_array($fleetOrder)) {
                    continue;
                }
                $action = is_string($fleetOrder['action'] ?? null) ? $fleetOrder['action'] : '';
                if (!in_array($action, ['rename', 'split', 'transfer', 'merge', 'refit'], true)) {
                    continue;
                }

                $fleetId = is_string($fleetOrder['fleetId'] ?? null) ? trim($fleetOrder['fleetId']) : '';
                if ($fleetId === '') {
                    $warnings[] = sprintf('Fleet %s order mangler fleetId.', $action);
                    continue;
                }
                $fleetIndex = $this->findFleetIndex($fleets, $fleetId);
                if ($fleetIndex === null || !is_array($fleets[$fleetIndex])) {
                    $warnings[] = sprintf('Flåden %s findes ikke.', $fleetId);
                    continue;
                }

                $fleet = TechnologyModelCatalog::normalizeFleet($fleets[$fleetIndex], $state);
                $fleets[$fleetIndex] = $fleet;
                if ((int) ($fleet['ownerPlayerId'] ?? 0) !== $playerIdInt) {
                    $warnings[] = sprintf('Flåden %s tilhører ikke spiller %s.', $fleetId, $playerId);
                    continue;
                }

                if ($action === 'rename') {
                    $name = is_string($fleetOrder['name'] ?? null) ? trim($fleetOrder['name']) : '';
                    if ($name === '' || mb_strlen($name) > 40) {
                        $warnings[] = sprintf('Flåden %s kunne ikke omdøbes: navnet skal være 1-40 tegn.', $fleetId);
                        continue;
                    }
                    $oldName = (string) ($fleet['name'] ?? $fleetId);
                    $fleets[$fleetIndex]['name'] = $name;
                    $fleetActions[] = [
                        'action' => 'rename',
                        'fleetId' => $fleetId,
                        'fromName' => $oldName,
                        'toName' => $name,
                    ];
                    continue;
                }

                if (isset($managedFleetIds[$fleetId])) {
                    $warnings[] = sprintf('Flåden %s har allerede en strukturel fleet-ordre denne runde.', $fleetId);
                    continue;
                }
                if (is_array($fleet['refit'] ?? null)) {
                    $warnings[] = sprintf('Flåden %s er allerede under refit og kan ikke omorganiseres.', $fleetId);
                    continue;
                }

                if ($action === 'split') {
                    $designId = is_string($fleetOrder['designId'] ?? null) ? trim($fleetOrder['designId']) : '';
                    $quantity = max(1, (int) ($fleetOrder['quantity'] ?? 0));
                    $entryIndex = $this->findCompositionIndex($fleet, $designId);
                    if ($designId === '' || $entryIndex === null) {
                        $warnings[] = sprintf('Split af %s mangler et gyldigt design.', $fleetId);
                        continue;
                    }
                    $composition = is_array($fleet['composition'] ?? null) ? array_values($fleet['composition']) : [];
                    $entry = $composition[$entryIndex] ?? null;
                    $available = is_array($entry) ? max(0, (int) ($entry['quantity'] ?? 0)) : 0;
                    if ($quantity > $available || $quantity >= max(1, (int) ($fleet['ships'] ?? 0))) {
                        $warnings[] = sprintf('Split af %s kræver 1-%d skibe og skal efterlade mindst ét skib i kildeflåden.', $fleetId, max(0, min($available, (int) ($fleet['ships'] ?? 0) - 1)));
                        continue;
                    }

                    $newName = is_string($fleetOrder['name'] ?? null) ? trim($fleetOrder['name']) : '';
                    ++$fleetManagementSequence;
                    if ($newName === '') {
                        $newName = sprintf('%s Detachment %d', (string) ($fleet['name'] ?? 'Fleet'), $fleetManagementSequence);
                    }
                    if (mb_strlen($newName) > 40) {
                        $warnings[] = sprintf('Den nye flådes navn må højst være 40 tegn.');
                        continue;
                    }

                    $movedFuelCapacity = $this->compositionFuelCapacity(is_array($entry) ? $entry : [], $quantity);
                    $movedFuel = $this->fuelShareForCapacity($fleet, $movedFuelCapacity);

                    $newEntry = $entry;
                    $newEntry['quantity'] = $quantity;
                    $composition[$entryIndex]['quantity'] = $available - $quantity;
                    if ((int) $composition[$entryIndex]['quantity'] <= 0) {
                        array_splice($composition, $entryIndex, 1);
                    }
                    $fleet['composition'] = array_values($composition);
                    $fleet['ships'] = max(0, (int) ($fleet['ships'] ?? 0) - $quantity);
                    $fleet['fuel'] = max(0, (int) ($fleet['fuel'] ?? 0) - $movedFuel);
                    $fleets[$fleetIndex] = TechnologyModelCatalog::normalizeFleet($fleet, $state);

                    $newFleetId = sprintf('fleet-%d-split-%d-%d', $playerIdInt, $turn->getNumber() + 1, $fleetManagementSequence);
                    $newFleet = TechnologyModelCatalog::normalizeFleet([
                        'id' => $newFleetId,
                        'ownerPlayerId' => $playerIdInt,
                        'systemId' => (string) ($fleet['systemId'] ?? ''),
                        'name' => $newName,
                        'ships' => $quantity,
                        'role' => 'Task force',
                        'legacyColonizationCapacity' => 0,
                        'fuel' => $movedFuel,
                        'composition' => [$newEntry],
                    ], $state);
                    $fleets[] = $newFleet;
                    $managedFleetIds[$fleetId] = true;
                    $managedFleetIds[$newFleetId] = true;
                    $fleetActions[] = [
                        'action' => 'split',
                        'fleetId' => $fleetId,
                        'newFleetId' => $newFleetId,
                        'designId' => $designId,
                        'designName' => (string) ($newEntry['designName'] ?? $designId),
                        'quantity' => $quantity,
                        'name' => $newName,
                    ];
                    continue;
                }

                $targetFleetId = is_string($fleetOrder['targetFleetId'] ?? null) ? trim($fleetOrder['targetFleetId']) : '';
                if (in_array($action, ['transfer', 'merge'], true)) {
                    if ($targetFleetId === '' || $targetFleetId === $fleetId) {
                        $warnings[] = sprintf('%s af %s kræver en anden målflåde.', ucfirst($action), $fleetId);
                        continue;
                    }
                    $targetIndex = $this->findFleetIndex($fleets, $targetFleetId);
                    if ($targetIndex === null || !is_array($fleets[$targetIndex])) {
                        $warnings[] = sprintf('Målflåden %s findes ikke.', $targetFleetId);
                        continue;
                    }
                    $targetFleet = TechnologyModelCatalog::normalizeFleet($fleets[$targetIndex], $state);
                    $fleets[$targetIndex] = $targetFleet;
                    if ((int) ($targetFleet['ownerPlayerId'] ?? 0) !== $playerIdInt) {
                        $warnings[] = sprintf('Målflåden %s tilhører ikke spilleren.', $targetFleetId);
                        continue;
                    }
                    if (($targetFleet['systemId'] ?? null) !== ($fleet['systemId'] ?? null)) {
                        $warnings[] = sprintf('%s og %s skal være i samme system for %s.', $fleetId, $targetFleetId, $action);
                        continue;
                    }
                    if (isset($managedFleetIds[$targetFleetId]) || is_array($targetFleet['refit'] ?? null)) {
                        $warnings[] = sprintf('Målflåden %s er allerede optaget af anden fleet management/refit.', $targetFleetId);
                        continue;
                    }
                }

                if ($action === 'transfer') {
                    $designId = is_string($fleetOrder['designId'] ?? null) ? trim($fleetOrder['designId']) : '';
                    $quantity = max(1, (int) ($fleetOrder['quantity'] ?? 0));
                    $sourceEntryIndex = $this->findCompositionIndex($fleet, $designId);
                    if ($designId === '' || $sourceEntryIndex === null) {
                        $warnings[] = sprintf('Transfer fra %s mangler et gyldigt design.', $fleetId);
                        continue;
                    }
                    $sourceComposition = is_array($fleet['composition'] ?? null) ? array_values($fleet['composition']) : [];
                    $entry = $sourceComposition[$sourceEntryIndex] ?? null;
                    $available = is_array($entry) ? max(0, (int) ($entry['quantity'] ?? 0)) : 0;
                    if ($quantity > $available || $quantity >= max(1, (int) ($fleet['ships'] ?? 0))) {
                        $warnings[] = sprintf('Transfer fra %s skal efterlade mindst ét skib i kildeflåden.', $fleetId);
                        continue;
                    }

                    $movedFuelCapacity = $this->compositionFuelCapacity(is_array($entry) ? $entry : [], $quantity);
                    $movedFuel = $this->fuelShareForCapacity($fleet, $movedFuelCapacity);

                    $sourceComposition[$sourceEntryIndex]['quantity'] = $available - $quantity;
                    if ((int) $sourceComposition[$sourceEntryIndex]['quantity'] <= 0) {
                        array_splice($sourceComposition, $sourceEntryIndex, 1);
                    }
                    $fleet['composition'] = array_values($sourceComposition);
                    $fleet['ships'] = max(0, (int) ($fleet['ships'] ?? 0) - $quantity);
                    $fleet['fuel'] = max(0, (int) ($fleet['fuel'] ?? 0) - $movedFuel);

                    $targetComposition = is_array($targetFleet['composition'] ?? null) ? array_values($targetFleet['composition']) : [];
                    $targetComposition = $this->addCompositionQuantity($targetComposition, is_array($entry) ? $entry : [], $quantity);
                    $targetFleet['composition'] = $targetComposition;
                    $targetFleet['ships'] = max(0, (int) ($targetFleet['ships'] ?? 0)) + $quantity;
                    $targetFleet['fuel'] = max(0, (int) ($targetFleet['fuel'] ?? 0)) + $movedFuel;

                    $fleets[$fleetIndex] = TechnologyModelCatalog::normalizeFleet($fleet, $state);
                    $fleets[$targetIndex] = TechnologyModelCatalog::normalizeFleet($targetFleet, $state);
                    $managedFleetIds[$fleetId] = true;
                    $managedFleetIds[$targetFleetId] = true;
                    $fleetActions[] = [
                        'action' => 'transfer',
                        'fleetId' => $fleetId,
                        'targetFleetId' => $targetFleetId,
                        'designId' => $designId,
                        'designName' => (string) (($entry['designName'] ?? null) ?: $designId),
                        'quantity' => $quantity,
                    ];
                    continue;
                }

                if ($action === 'merge') {
                    $targetComposition = is_array($targetFleet['composition'] ?? null) ? array_values($targetFleet['composition']) : [];
                    foreach (is_array($fleet['composition'] ?? null) ? $fleet['composition'] : [] as $entry) {
                        if (!is_array($entry)) {
                            continue;
                        }
                        $targetComposition = $this->addCompositionQuantity(
                            $targetComposition,
                            $entry,
                            max(0, (int) ($entry['quantity'] ?? 0)),
                        );
                    }
                    $targetFleet['composition'] = $targetComposition;
                    $targetFleet['ships'] = max(0, (int) ($targetFleet['ships'] ?? 0)) + max(0, (int) ($fleet['ships'] ?? 0));
                    $targetFleet['legacyColonizationCapacity'] = max(0, (int) ($targetFleet['legacyColonizationCapacity'] ?? 0))
                        + max(0, (int) ($fleet['legacyColonizationCapacity'] ?? 0));
                    $targetFleet['fuel'] = max(0, (int) ($targetFleet['fuel'] ?? 0))
                        + max(0, (int) ($fleet['fuel'] ?? 0));
                    $fleets[$targetIndex] = TechnologyModelCatalog::normalizeFleet($targetFleet, $state);
                    array_splice($fleets, $fleetIndex, 1);

                    $managedFleetIds[$fleetId] = true;
                    $managedFleetIds[$targetFleetId] = true;
                    $fleetActions[] = [
                        'action' => 'merge',
                        'fleetId' => $fleetId,
                        'targetFleetId' => $targetFleetId,
                        'shipsMerged' => max(0, (int) ($fleet['ships'] ?? 0)),
                    ];
                    continue;
                }

                if ($action === 'refit') {
                    $systemId = is_string($fleet['systemId'] ?? null) ? $fleet['systemId'] : '';
                    if ($systemId === '' || ($startingOwners[$systemId] ?? null) !== $playerIdInt) {
                        $warnings[] = sprintf('Refit af %s kræver, at flåden ligger ved en af dine kolonier ved rundens start.', $fleetId);
                        continue;
                    }
                    $sourceDesignId = is_string($fleetOrder['designId'] ?? null) ? trim($fleetOrder['designId']) : '';
                    $targetDesignId = is_string($fleetOrder['targetDesignId'] ?? null) ? trim($fleetOrder['targetDesignId']) : '';
                    $quantity = max(1, (int) ($fleetOrder['quantity'] ?? 0));
                    $sourceEntryIndex = $this->findCompositionIndex($fleet, $sourceDesignId);
                    $sourceEntry = $sourceEntryIndex !== null && is_array($fleet['composition'][$sourceEntryIndex] ?? null)
                        ? $fleet['composition'][$sourceEntryIndex]
                        : null;
                    $available = is_array($sourceEntry) ? max(0, (int) ($sourceEntry['quantity'] ?? 0)) : 0;
                    $sourceDesign = $sourceDesignId !== '' ? TechnologyModelCatalog::resolveDesign($state, $playerIdInt, $sourceDesignId) : null;
                    $targetDesign = $targetDesignId !== '' ? TechnologyModelCatalog::resolveDesign($state, $playerIdInt, $targetDesignId) : null;
                    if ($sourceDesign === null || $targetDesign === null || $sourceEntry === null || $quantity > $available) {
                        $warnings[] = sprintf('Refit-ordren for %s refererer til et ukendt design eller for mange skibe.', $fleetId);
                        continue;
                    }
                    if (($sourceDesign['family'] ?? null) !== ($targetDesign['family'] ?? null)) {
                        $warnings[] = sprintf('Refit af %s kræver samme hull family.', $fleetId);
                        continue;
                    }
                    if ((int) ($targetDesign['generation'] ?? 0) <= (int) ($sourceDesign['generation'] ?? 0)) {
                        $warnings[] = sprintf('Refit af %s skal gå til en nyere generation.', $fleetId);
                        continue;
                    }
                    if (($targetDesign['unlocked'] ?? false) !== true || ($targetDesign['obsolete'] ?? false) === true) {
                        $warnings[] = sprintf('Måldesignet %s er ikke tilgængeligt til refit.', (string) ($targetDesign['name'] ?? $targetDesignId));
                        continue;
                    }

                    $systemIndex = $systemIds[$systemId] ?? null;
                    if (!is_int($systemIndex) || !isset($systems[$systemIndex]) || !is_array($systems[$systemIndex])) {
                        $warnings[] = sprintf('Refit-systemet %s findes ikke.', $systemId);
                        continue;
                    }
                    $industryIndex = $this->findResourceIndex($systems[$systemIndex], 'industry');
                    if ($industryIndex === null) {
                        $warnings[] = sprintf('%s har ingen industry-ressource til refit.', $systemId);
                        continue;
                    }
                    $industryCost = $this->refitCost($sourceDesign, $targetDesign, $quantity);
                    $availableIndustry = max(0, (int) ($systems[$systemIndex]['resources'][$industryIndex]['value'] ?? 0));
                    if ($availableIndustry < $industryCost) {
                        $warnings[] = sprintf(
                            '%s mangler industry til refit af %s: %d tilgængelig, %d kræves.',
                            (string) ($systems[$systemIndex]['name'] ?? $systemId),
                            (string) ($fleet['name'] ?? $fleetId),
                            $availableIndustry,
                            $industryCost,
                        );
                        continue;
                    }

                    $systems[$systemIndex]['resources'][$industryIndex]['value'] = $availableIndustry - $industryCost;
                    $refit = [
                        'fromDesignId' => $sourceDesignId,
                        'fromDesignName' => (string) ($sourceDesign['name'] ?? $sourceDesignId),
                        'toDesignId' => $targetDesignId,
                        'toDesignName' => (string) ($targetDesign['name'] ?? $targetDesignId),
                        'quantity' => $quantity,
                        'industryCost' => $industryCost,
                        'turnsTotal' => 2,
                        'turnsRemaining' => 1,
                        'startedTurn' => $turn->getNumber() + 1,
                        'systemId' => $systemId,
                    ];
                    $fleets[$fleetIndex]['refit'] = $refit;
                    $managedFleetIds[$fleetId] = true;
                    $refitsStarted[] = ['fleetId' => $fleetId, 'fleetName' => (string) ($fleet['name'] ?? $fleetId), ...$refit];
                }
            }

            // Movement is resolved before colonization. A fleet that moved this turn
            // cannot colonize until the following turn.
            foreach ($fleetOrders as $fleetOrder) {
                if (!is_array($fleetOrder) || ($fleetOrder['action'] ?? null) !== 'move') {
                    continue;
                }

                $fleetId = is_string($fleetOrder['fleetId'] ?? null) ? $fleetOrder['fleetId'] : '';
                $targetSystemId = is_string($fleetOrder['targetSystemId'] ?? null) ? $fleetOrder['targetSystemId'] : '';
                if ($fleetId === '' || $targetSystemId === '') {
                    $warnings[] = 'En fleet move-ordre manglede fleetId eller targetSystemId.';
                    continue;
                }

                $fleetIndex = $this->findFleetIndex($fleets, $fleetId);
                if ($fleetIndex === null) {
                    $warnings[] = sprintf('Flåden %s findes ikke.', $fleetId);
                    continue;
                }

                $fleet = $fleets[$fleetIndex];
                if ((string) ($fleet['ownerPlayerId'] ?? '') !== (string) $playerId) {
                    $warnings[] = sprintf('Flåden %s tilhører ikke spiller %s.', $fleetId, $playerId);
                    continue;
                }
                if (isset($managedFleetIds[$fleetId]) || is_array($fleet['refit'] ?? null)) {
                    $warnings[] = sprintf('Flåden %s kan ikke flytte, mens den omorganiseres eller er under refit.', $fleetId);
                    continue;
                }
                $fleet = TechnologyModelCatalog::normalizeFleet($fleet, $state);
                $fleets[$fleetIndex] = $fleet;
                $movementRange = max(1, (int) ($fleet['movementRange'] ?? 1));
                if (!isset($systemIds[$targetSystemId])) {
                    $warnings[] = sprintf('Destinationssystemet %s findes ikke.', $targetSystemId);
                    continue;
                }

                $fromSystemId = is_string($fleet['systemId'] ?? null) ? $fleet['systemId'] : '';
                if ($fromSystemId === $targetSystemId) {
                    continue;
                }
                $routeDistance = $this->systemDistance($routes, $fromSystemId, $targetSystemId, $movementRange);
                if ($routeDistance === null || $routeDistance > $movementRange) {
                    $warnings[] = sprintf(
                        'Flåden %s kan højst flytte %d hop denne runde; %s er uden for rækkevidde.',
                        $fleetId,
                        $movementRange,
                        $targetSystemId,
                    );
                    continue;
                }

                $fuelUsePerHop = max(0, (int) ($fleet['fuelUsePerHop'] ?? 0));
                $fuelAvailable = max(0, (int) ($fleet['fuel'] ?? 0));
                $fuelRequired = $routeDistance * $fuelUsePerHop;
                if ($fuelRequired > $fuelAvailable) {
                    $warnings[] = sprintf(
                        'Flåden %s mangler brændstof til %s: %d tilgængelig, %d kræves for %d hop.',
                        $fleetId,
                        $targetSystemId,
                        $fuelAvailable,
                        $fuelRequired,
                        $routeDistance,
                    );
                    continue;
                }

                $fleets[$fleetIndex]['systemId'] = $targetSystemId;
                $fleets[$fleetIndex]['fuel'] = max(0, $fuelAvailable - $fuelRequired);
                unset($fleets[$fleetIndex]['destinationSystemId']);
                $fleets[$fleetIndex] = TechnologyModelCatalog::normalizeFleet($fleets[$fleetIndex], $state);
                $movedFleetIds[$fleetId] = true;
                $movements[] = [
                    'fleetId' => $fleetId,
                    'fromSystemId' => $fromSystemId,
                    'toSystemId' => $targetSystemId,
                    'distance' => $routeDistance,
                    'fuelUsed' => $fuelRequired,
                    'fuelRemaining' => (int) ($fleets[$fleetIndex]['fuel'] ?? 0),
                    'fuelCapacity' => (int) ($fleets[$fleetIndex]['fuelCapacity'] ?? 0),
                ];
            }

            foreach ($fleetOrders as $fleetOrder) {
                if (!is_array($fleetOrder) || ($fleetOrder['action'] ?? null) !== 'colonize') {
                    continue;
                }

                $fleetId = is_string($fleetOrder['fleetId'] ?? null) ? $fleetOrder['fleetId'] : '';
                $targetSystemId = is_string($fleetOrder['targetSystemId'] ?? null) ? $fleetOrder['targetSystemId'] : '';
                if ($fleetId === '' || $targetSystemId === '') {
                    $warnings[] = 'En koloniseringsordre manglede fleetId eller targetSystemId.';
                    continue;
                }
                if (isset($movedFleetIds[$fleetId])) {
                    $warnings[] = sprintf('Flåden %s kan ikke både flytte og kolonisere i samme runde.', $fleetId);
                    continue;
                }

                $fleetIndex = $this->findFleetIndex($fleets, $fleetId);
                if ($fleetIndex === null) {
                    $warnings[] = sprintf('Flåden %s findes ikke.', $fleetId);
                    continue;
                }

                $fleet = $fleets[$fleetIndex];
                if ((string) ($fleet['ownerPlayerId'] ?? '') !== (string) $playerId) {
                    $warnings[] = sprintf('Flåden %s tilhører ikke spiller %s.', $fleetId, $playerId);
                    continue;
                }
                if (isset($managedFleetIds[$fleetId]) || is_array($fleet['refit'] ?? null)) {
                    $warnings[] = sprintf('Flåden %s kan ikke kolonisere, mens den omorganiseres eller er under refit.', $fleetId);
                    continue;
                }
                if (($fleet['systemId'] ?? null) !== $targetSystemId) {
                    $warnings[] = sprintf('Flåden %s befinder sig ikke i %s.', $fleetId, $targetSystemId);
                    continue;
                }

                $systemIndex = $systemIds[$targetSystemId] ?? null;
                if (!is_int($systemIndex) || !isset($systems[$systemIndex]) || !is_array($systems[$systemIndex])) {
                    $warnings[] = sprintf('Koloniseringssystemet %s findes ikke.', $targetSystemId);
                    continue;
                }
                if (($systems[$systemIndex]['ownerPlayerId'] ?? null) !== null) {
                    $warnings[] = sprintf('Systemet %s er allerede koloniseret.', $targetSystemId);
                    continue;
                }

                $capacity = $this->colonyCapacity($fleet);
                if ($capacity < 1) {
                    $warnings[] = sprintf('Flåden %s har intet ubrugt colony module.', $fleetId);
                    continue;
                }

                $systems[$systemIndex]['ownerPlayerId'] = (int) $playerId;
                $systems[$systemIndex]['population'] = max(0.25, (float) ($systems[$systemIndex]['population'] ?? 0.0));
                $systems[$systemIndex]['happiness'] = 70;
                $systems[$systemIndex]['security'] = 15;
                $systems[$systemIndex]['development'] = 8;
                $systems[$systemIndex]['defenses'] = max(0, (int) ($systems[$systemIndex]['defenses'] ?? 0));
                $systems[$systemIndex]['description'] = sprintf(
                    'New colony established in year %d by player %s.',
                    (int) $nextState['year'],
                    $playerId,
                );
                $systems[$systemIndex]['isCapital'] = false;
                $systems[$systemIndex]['sensorRange'] = 1;
                // A frontier colony receives enough prefabricated industrial stores
                // to establish its first extraction installation. Long-term output
                // still depends on natural potential and the infrastructure built.
                $colonyIndustryIndex = $this->findResourceIndex($systems[$systemIndex], 'industry');
                if ($colonyIndustryIndex !== null) {
                    $systems[$systemIndex]['resources'][$colonyIndustryIndex]['value'] = max(
                        260,
                        (int) ($systems[$systemIndex]['resources'][$colonyIndustryIndex]['value'] ?? 0),
                    );
                }

                $consumed = $this->consumeColonyCapacity($fleet);
                if ($consumed['fleet'] === null) {
                    array_splice($fleets, $fleetIndex, 1);
                } else {
                    $fleets[$fleetIndex] = $consumed['fleet'];
                }
                $colonizations[] = [
                    'fleetId' => $fleetId,
                    'systemId' => $targetSystemId,
                    'population' => $systems[$systemIndex]['population'],
                    'consumedDesignName' => $consumed['designName'],
                    'colonyShipConsumed' => $consumed['shipConsumed'],
                ];
            }

            $productionOrders = is_array($orders['production'] ?? null) ? $orders['production'] : [];
            $buildSequence = 0;
            foreach ($productionOrders as $productionOrder) {
                if (!is_array($productionOrder)) {
                    continue;
                }

                $systemId = is_string($productionOrder['systemId'] ?? null) ? $productionOrder['systemId'] : '';
                $item = is_string($productionOrder['item'] ?? null) ? trim($productionOrder['item']) : '';
                $productionKind = is_string($productionOrder['productionKind'] ?? null) ? trim($productionOrder['productionKind']) : '';
                $quantity = $productionKind === 'upgrade' ? 1 : max(1, min(10, (int) ($productionOrder['quantity'] ?? 1)));
                $modelId = is_string($productionOrder['modelId'] ?? null) ? trim($productionOrder['modelId']) : '';
                $sourceModelId = is_string($productionOrder['sourceModelId'] ?? null) ? trim($productionOrder['sourceModelId']) : '';
                $definition = $this->productionDefinition($item, $state, $playerIdInt, $modelId, $productionKind, $sourceModelId);

                if ($systemId === '' || $item === '' || $definition === null) {
                    $warnings[] = sprintf('Ukendt eller ugyldig produktionsordre: %s.', $item !== '' ? $item : 'tom ordre');
                    continue;
                }
                if (($startingOwners[$systemId] ?? null) !== (int) $playerId) {
                    $warnings[] = sprintf('Produktion i %s kræver, at systemet var din koloni ved rundens start.', $systemId);
                    continue;
                }

                $systemIndex = $systemIds[$systemId] ?? null;
                if (!is_int($systemIndex) || !isset($systems[$systemIndex]) || !is_array($systems[$systemIndex])) {
                    $warnings[] = sprintf('Produktionssystemet %s findes ikke.', $systemId);
                    continue;
                }

                $definitionModel = is_array($definition['model'] ?? null) ? $definition['model'] : null;
                $definitionFamily = is_array($definitionModel) ? (string) ($definitionModel['family'] ?? '') : '';
                if ($definitionFamily === 'asteroid_mining') {
                    $asteroids = is_array($systems[$systemIndex]['asteroids'] ?? null) ? $systems[$systemIndex]['asteroids'] : [];
                    if (($asteroids['present'] ?? false) !== true) {
                        $warnings[] = sprintf('%s har ingen betydelig asteroidforekomst at mine.', (string) ($systems[$systemIndex]['name'] ?? $systemId));
                        continue;
                    }
                }

                for ($unit = 0; $unit < $quantity; ++$unit) {
                    $industryIndex = $this->findResourceIndex($systems[$systemIndex], 'industry');
                    if ($industryIndex === null) {
                        $warnings[] = sprintf('%s har ingen industry-ressource.', $systemId);
                        break;
                    }

                    $available = (int) ($systems[$systemIndex]['resources'][$industryIndex]['value'] ?? 0);
                    if ($available < $definition['cost']) {
                        $warnings[] = sprintf(
                            '%s mangler industry til %s: %d tilgængelig, %d kræves.',
                            (string) ($systems[$systemIndex]['name'] ?? $systemId),
                            $item,
                            $available,
                            $definition['cost'],
                        );
                        break;
                    }

                    $systems[$systemIndex]['resources'][$industryIndex]['value'] = $available - $definition['cost'];
                    ++$buildSequence;

                    if (($definition['kind'] ?? null) === 'ship') {
                        $design = is_array($definition['design'] ?? null) ? $definition['design'] : null;
                        if ($design === null) {
                            $systems[$systemIndex]['resources'][$industryIndex]['value'] += $definition['cost'];
                            $warnings[] = sprintf('Skibsdesignet %s kunne ikke indlæses.', $item);
                            break;
                        }
                        $existingFleetCount = $this->countPlayerFleetsAtSystem($fleets, (int) $playerId, $systemId);
                        $fleetNumber = $existingFleetCount + 1;
                        $batchSize = max(1, (int) ($design['batchSize'] ?? 40));
                        $designColonyCapacity = max(0, (int) ($design['stats']['colonizationCapacity'] ?? 0));
                        $fleet = [
                            'id' => sprintf('fleet-%s-built-%d-%d', $playerId, $turn->getNumber() + 1, $buildSequence),
                            'ownerPlayerId' => (int) $playerId,
                            'systemId' => $systemId,
                            'name' => sprintf('%s %s %d', (string) ($systems[$systemIndex]['name'] ?? 'Colony'), (string) ($design['name'] ?? 'Scout'), $fleetNumber),
                            'ships' => $batchSize,
                            'role' => $designColonyCapacity > 0 ? 'Colony ship' : 'Scout fleet',
                            'colonizationCapacity' => $batchSize * $designColonyCapacity,
                            'composition' => [[
                                'designId' => (string) $design['id'],
                                'designName' => (string) $design['name'],
                                'generation' => (int) ($design['generation'] ?? 1),
                                'quantity' => $batchSize,
                                'components' => $design['components'] ?? [],
                                'stats' => $design['stats'] ?? [],
                            ]],
                        ];
                        $fleets[] = TechnologyModelCatalog::normalizeFleet($fleet, $state);
                    } elseif (($definition['kind'] ?? null) === 'installation') {
                        $model = is_array($definition['model'] ?? null) ? $definition['model'] : null;
                        if ($model === null) {
                            $systems[$systemIndex]['resources'][$industryIndex]['value'] += $definition['cost'];
                            $warnings[] = sprintf('Installationsmodellen %s kunne ikke indlæses.', $item);
                            break;
                        }
                        $family = (string) ($model['family'] ?? '');
                        if (TechnologyModelCatalog::installationForFamily($systems[$systemIndex], $family) !== null) {
                            $systems[$systemIndex]['resources'][$industryIndex]['value'] += $definition['cost'];
                            $warnings[] = sprintf('%s har allerede en %s-installation. Brug en eksplicit upgrade-ordre.', (string) ($systems[$systemIndex]['name'] ?? $systemId), $family);
                            break;
                        }
                        $systems[$systemIndex] = TechnologyModelCatalog::install($systems[$systemIndex], $model, $turn->getNumber() + 1);
                    } elseif (($definition['kind'] ?? null) === 'upgrade') {
                        $model = is_array($definition['model'] ?? null) ? $definition['model'] : null;
                        $family = is_array($model) ? (string) ($model['family'] ?? '') : '';
                        $sourceModelId = (string) ($definition['sourceModelId'] ?? '');
                        $installed = TechnologyModelCatalog::installationForFamily($systems[$systemIndex], $family);
                        if ($model === null || $installed === null || ($installed['modelId'] ?? null) !== $sourceModelId) {
                            $systems[$systemIndex]['resources'][$industryIndex]['value'] += $definition['cost'];
                            $warnings[] = sprintf('%s kan ikke opgradere %s, fordi den forventede kildeinstallation ikke længere er installeret.', (string) ($systems[$systemIndex]['name'] ?? $systemId), $item);
                            break;
                        }
                        if (TechnologyModelCatalog::pendingUpgradeForFamily($systems[$systemIndex], $family) !== null) {
                            $systems[$systemIndex]['resources'][$industryIndex]['value'] += $definition['cost'];
                            $warnings[] = sprintf('%s har allerede en aktiv %s-opgradering.', (string) ($systems[$systemIndex]['name'] ?? $systemId), $family);
                            break;
                        }

                        $turns = max(1, (int) ($definition['turns'] ?? 1));
                        if ($turns <= 1) {
                            $systems[$systemIndex] = TechnologyModelCatalog::upgradeInstallation($systems[$systemIndex], $model, $turn->getNumber() + 1);
                            $installationUpgradesCompleted[] = [
                                'systemId' => $systemId,
                                'family' => $family,
                                'fromModelId' => $sourceModelId,
                                'fromName' => (string) ($definition['sourceName'] ?? $sourceModelId),
                                'fromVersion' => (int) ($definition['sourceVersion'] ?? 1),
                                'toModelId' => (string) $model['id'],
                                'toName' => (string) $model['name'],
                                'toVersion' => (int) $model['version'],
                                'industryCost' => (int) $definition['cost'],
                                'completedTurn' => $turn->getNumber() + 1,
                            ];
                        } else {
                            $systems[$systemIndex] = TechnologyModelCatalog::startInstallationUpgrade($systems[$systemIndex], $model, $turn->getNumber() + 1);
                        }
                    }

                    if (($definition['kind'] ?? null) !== 'upgrade') {
                        $productions[] = [
                            'systemId' => $systemId,
                            'item' => (string) ($definition['name'] ?? $item),
                            'modelId' => (string) ($definition['modelId'] ?? ''),
                            'modelVersion' => (int) ($definition['version'] ?? 1),
                            'productionKind' => (string) ($definition['kind'] ?? 'legacy'),
                            'industryCost' => $definition['cost'],
                            'batchSize' => isset($definition['design']) && is_array($definition['design']) ? (int) ($definition['design']['batchSize'] ?? 0) : null,
                            'colonizationCapacity' => isset($definition['design']) && is_array($definition['design']) ? (int) ($definition['design']['stats']['colonizationCapacity'] ?? 0) : 0,
                        ];
                    }
                }
            }

            // Research is persistent game state. Points generated by the player's
            // colonies are added every turn and spent on one active technology.
            // A new valid order changes the active technology; otherwise the previous
            // selection continues automatically.
            $playerResearch['income'] = $researchIncome;
            $playerResearch['stockpile'] = max(0, (int) ($playerResearch['stockpile'] ?? 0)) + $researchIncome;

            $researchOrders = is_array($orders['research'] ?? null) ? array_values($orders['research']) : [];
            if ($researchOrders !== []) {
                $selection = is_array($researchOrders[0]) ? $researchOrders[0] : [];
                $technologyId = is_string($selection['technologyId'] ?? null)
                    ? trim($selection['technologyId'])
                    : (is_string($selection['field'] ?? null) ? trim($selection['field']) : '');

                if ($technologyId === '' || !ResearchCatalog::canResearch($playerResearch, $technologyId)) {
                    $warnings[] = sprintf('Forskningsvalget %s er ugyldigt eller låst.', $technologyId !== '' ? $technologyId : 'tomt valg');
                } else {
                    $playerResearch['activeTechnologyId'] = $technologyId;
                }
            }

            $activeTechnologyId = is_string($playerResearch['activeTechnologyId'] ?? null)
                ? $playerResearch['activeTechnologyId']
                : null;
            if ($activeTechnologyId !== null && ResearchCatalog::canResearch($playerResearch, $activeTechnologyId)) {
                $definition = ResearchCatalog::technology($activeTechnologyId);
                if ($definition !== null) {
                    $cost = max(1, (int) $definition['cost']);
                    $progressBefore = max(0, (int) ($playerResearch['progress'][$activeTechnologyId] ?? 0));
                    $needed = max(0, $cost - $progressBefore);
                    $spent = min(max(0, (int) $playerResearch['stockpile']), $needed);
                    $progressAfter = min($cost, $progressBefore + $spent);
                    $playerResearch['stockpile'] -= $spent;
                    $playerResearch['progress'][$activeTechnologyId] = $progressAfter;

                    if ($progressAfter >= $cost) {
                        $completed = is_array($playerResearch['completed'] ?? null) ? $playerResearch['completed'] : [];
                        if (!in_array($activeTechnologyId, $completed, true)) {
                            $completed[] = $activeTechnologyId;
                        }
                        $playerResearch['completed'] = array_values($completed);
                        $playerResearch['activeTechnologyId'] = null;
                        $researchCompleted[] = [
                            'technologyId' => $activeTechnologyId,
                            'name' => (string) $definition['name'],
                            'field' => (string) $definition['field'],
                            'tier' => (int) $definition['tier'],
                            'cost' => $cost,
                            'effect' => (string) $definition['effect'],
                            'kind' => (string) ($definition['kind'] ?? 'hardware'),
                            'unlocks' => is_array($definition['unlocks'] ?? null) ? array_values($definition['unlocks']) : [],
                        ];
                    } else {
                        $researchProgress = [
                            'technologyId' => $activeTechnologyId,
                            'name' => (string) $definition['name'],
                            'field' => (string) $definition['field'],
                            'progress' => $progressAfter,
                            'cost' => $cost,
                            'spent' => $spent,
                            'income' => $researchIncome,
                        ];
                    }
                }
            }

            // Re-normalize to recalculate levels/modifiers after a completion.
            $playerResearch = ResearchCatalog::normalizeState($playerResearch);
            $playerResearch['income'] = $researchIncome;
            $researchByPlayer[(string) $playerId] = $playerResearch;

            $parts = [];
            if (count($fleetActions) > 0) {
                $parts[] = sprintf('%d fleet management-handling(er)', count($fleetActions));
            }
            if (count($refitsStarted) > 0) {
                $parts[] = sprintf('%d refit startet', count($refitsStarted));
            }
            if (count($refitsCompleted) > 0) {
                $parts[] = sprintf('%d refit afsluttet', count($refitsCompleted));
            }
            if (count($fuelRefills) > 0) {
                $parts[] = sprintf('%d optankning(er)', count($fuelRefills));
            }
            if (count($movements) > 0) {
                $parts[] = sprintf('%d flådebevægelse(r)', count($movements));
            }
            if (count($colonizations) > 0) {
                $parts[] = sprintf('%d kolonisering(er)', count($colonizations));
            }
            if (count($productions) > 0) {
                $parts[] = sprintf('%d produktion(er)', count($productions));
            }
            if (count($installationUpgradesCompleted) > 0) {
                $parts[] = sprintf('%d installationsopgradering(er)', count($installationUpgradesCompleted));
            }
            if (count($designsCreated) > 0) {
                $parts[] = sprintf('%d nyt skibsdesign', count($designsCreated));
            }
            if (count($researchCompleted) > 0) {
                $parts[] = sprintf('%d forskningsteknologi(er)', count($researchCompleted));
            }

            $reports[$playerId] = [
                'message' => $parts === []
                    ? 'Ingen fleet management, refits, optankninger, flådebevægelser, koloniseringer, produktioner, designs, installationsopgraderinger eller forskningsteknologier blev afsluttet i denne runde.'
                    : ucfirst(implode(', ', $parts)).' blev udført.',
                'fleet_actions' => $fleetActions,
                'refits_started' => $refitsStarted,
                'refits_completed' => $refitsCompleted,
                'fuel_refills' => $fuelRefills,
                'resource_income' => $resourceIncome,
                'movements' => $movements,
                'colonizations' => $colonizations,
                'productions' => $productions,
                'installation_upgrades_completed' => $installationUpgradesCompleted,
                'designs_created' => $designsCreated,
                'research_completed' => $researchCompleted,
                'research_progress' => $researchProgress,
                'research_income' => $researchIncome,
                'research_stockpile' => (int) ($playerResearch['stockpile'] ?? 0),
                'warnings' => $warnings,
                'orders' => $orders,
            ];
        }

        $nextState['universe']['systems'] = array_values($systems);
        $nextState['universe']['fleets'] = array_values($fleets);
        $nextState['research'] = $researchByPlayer;
        $nextState = TechnologyModelCatalog::normalizeState($nextState);

        return new TurnGenerationResult($nextState, $reports);
    }

    /**
     * @param array<string, mixed> $fleet
     * @param array<string, mixed> $state
     * @return array{fleet:array<string,mixed>,completed:array<string,mixed>|null,warning:string|null}
     */
    private function advanceFleetRefit(array $fleet, array $state, int $turnNumber): array
    {
        $refit = is_array($fleet['refit'] ?? null) ? $fleet['refit'] : null;
        if ($refit === null) {
            return ['fleet' => $fleet, 'completed' => null, 'warning' => null];
        }

        $turnsRemaining = max(1, (int) ($refit['turnsRemaining'] ?? 1));
        if ($turnsRemaining > 1) {
            $refit['turnsRemaining'] = $turnsRemaining - 1;
            $fleet['refit'] = $refit;
            return ['fleet' => $fleet, 'completed' => null, 'warning' => null];
        }

        $playerId = (int) ($fleet['ownerPlayerId'] ?? 0);
        $fromDesignId = is_string($refit['fromDesignId'] ?? null) ? $refit['fromDesignId'] : '';
        $toDesignId = is_string($refit['toDesignId'] ?? null) ? $refit['toDesignId'] : '';
        $quantity = max(1, (int) ($refit['quantity'] ?? 0));
        $sourceIndex = $this->findCompositionIndex($fleet, $fromDesignId);
        $targetDesign = $toDesignId !== '' ? TechnologyModelCatalog::resolveDesign($state, $playerId, $toDesignId) : null;

        if ($sourceIndex === null || $targetDesign === null) {
            unset($fleet['refit']);
            return [
                'fleet' => TechnologyModelCatalog::normalizeFleet($fleet, $state),
                'completed' => null,
                'warning' => sprintf('Refit af %s kunne ikke afsluttes, fordi source/target design ikke længere findes.', (string) ($fleet['name'] ?? $fleet['id'] ?? 'fleet')),
            ];
        }

        $composition = is_array($fleet['composition'] ?? null) ? array_values($fleet['composition']) : [];
        $sourceEntry = is_array($composition[$sourceIndex] ?? null) ? $composition[$sourceIndex] : null;
        $available = is_array($sourceEntry) ? max(0, (int) ($sourceEntry['quantity'] ?? 0)) : 0;
        if ($sourceEntry === null || $available < $quantity) {
            unset($fleet['refit']);
            return [
                'fleet' => TechnologyModelCatalog::normalizeFleet($fleet, $state),
                'completed' => null,
                'warning' => sprintf('Refit af %s kunne ikke afsluttes, fordi kildeflådens sammensætning ændrede sig.', (string) ($fleet['name'] ?? $fleet['id'] ?? 'fleet')),
            ];
        }

        $composition[$sourceIndex]['quantity'] = $available - $quantity;
        if ((int) $composition[$sourceIndex]['quantity'] <= 0) {
            array_splice($composition, $sourceIndex, 1);
        }
        $targetEntry = [
            'designId' => (string) $targetDesign['id'],
            'designName' => (string) $targetDesign['name'],
            'generation' => (int) ($targetDesign['generation'] ?? 1),
            'quantity' => $quantity,
            'components' => $targetDesign['components'] ?? [],
            'stats' => $targetDesign['stats'] ?? [],
        ];
        $composition = $this->addCompositionQuantity($composition, $targetEntry, $quantity);
        $fleet['composition'] = array_values($composition);
        unset($fleet['refit']);
        $fleet = TechnologyModelCatalog::normalizeFleet($fleet, $state);

        return [
            'fleet' => $fleet,
            'completed' => [
                'fleetId' => (string) ($fleet['id'] ?? ''),
                'fleetName' => (string) ($fleet['name'] ?? $fleet['id'] ?? 'Fleet'),
                'fromDesignId' => $fromDesignId,
                'fromDesignName' => (string) ($refit['fromDesignName'] ?? $fromDesignId),
                'toDesignId' => $toDesignId,
                'toDesignName' => (string) ($targetDesign['name'] ?? $toDesignId),
                'quantity' => $quantity,
                'industryCost' => max(0, (int) ($refit['industryCost'] ?? 0)),
                'completedTurn' => $turnNumber,
            ],
            'warning' => null,
        ];
    }

    /** @param array<string, mixed> $fleet */
    private function findCompositionIndex(array $fleet, string $designId): ?int
    {
        if ($designId === '') {
            return null;
        }
        foreach (is_array($fleet['composition'] ?? null) ? array_values($fleet['composition']) : [] as $index => $entry) {
            if (is_array($entry) && ($entry['designId'] ?? null) === $designId) {
                return $index;
            }
        }
        return null;
    }

    /**
     * @param list<mixed> $composition
     * @param array<string, mixed> $entry
     * @return list<mixed>
     */
    private function addCompositionQuantity(array $composition, array $entry, int $quantity): array
    {
        $quantity = max(0, $quantity);
        $designId = is_string($entry['designId'] ?? null) ? $entry['designId'] : '';
        if ($quantity < 1 || $designId === '') {
            return array_values($composition);
        }

        foreach ($composition as $index => $candidate) {
            if (!is_array($candidate) || ($candidate['designId'] ?? null) !== $designId) {
                continue;
            }
            $composition[$index]['quantity'] = max(0, (int) ($candidate['quantity'] ?? 0)) + $quantity;
            return array_values($composition);
        }

        $entry['quantity'] = $quantity;
        $composition[] = $entry;
        return array_values($composition);
    }

    /**
     * Refit only charges for hardware that changes. Reused components carry no
     * new-build cost, replacement components receive 50% salvage credit for the
     * removed hardware, and pure removals have a small yard/labor charge.
     *
     * Design component costs are batch costs, so ordinary 40-ship Scout refits
     * scale against the target batch size. Colony ships remain individual units.
     *
     * @param array<string, mixed> $source
     * @param array<string, mixed> $target
     */
    private function refitCost(array $source, array $target, int $quantity): int
    {
        $sourceByCategory = [];
        foreach (is_array($source['components'] ?? null) ? $source['components'] : [] as $component) {
            if (is_array($component) && is_string($component['category'] ?? null)) {
                $sourceByCategory[(string) $component['category']] = $component;
            }
        }
        $targetByCategory = [];
        foreach (is_array($target['components'] ?? null) ? $target['components'] : [] as $component) {
            if (is_array($component) && is_string($component['category'] ?? null)) {
                $targetByCategory[(string) $component['category']] = $component;
            }
        }

        $categories = array_unique(array_merge(array_keys($sourceByCategory), array_keys($targetByCategory)));
        $changedBatchCost = 0;
        foreach ($categories as $category) {
            $from = $sourceByCategory[$category] ?? null;
            $to = $targetByCategory[$category] ?? null;
            $fromId = is_array($from) && is_string($from['modelId'] ?? null) ? $from['modelId'] : '';
            $toId = is_array($to) && is_string($to['modelId'] ?? null) ? $to['modelId'] : '';
            if ($fromId === $toId) {
                continue;
            }

            $fromModel = $fromId !== '' ? TechnologyModelCatalog::model($fromId) : null;
            $toModel = $toId !== '' ? TechnologyModelCatalog::model($toId) : null;
            $fromCost = is_array($fromModel) ? max(0, (int) ($fromModel['stats']['industryCost'] ?? 0)) : 0;
            $toCost = is_array($toModel) ? max(0, (int) ($toModel['stats']['industryCost'] ?? 0)) : 0;

            if ($toCost > 0) {
                $changedBatchCost += max(1, $toCost - intdiv($fromCost, 2));
            } elseif ($fromCost > 0) {
                $changedBatchCost += max(1, (int) ceil($fromCost * 0.10));
            }
        }

        $targetBatch = max(1, (int) ($target['batchSize'] ?? 1));
        return max(1, (int) ceil(max(1, $changedBatchCost) * max(1, $quantity) / $targetBatch));
    }

    /** @param array<string, mixed> $entry */
    private function compositionFuelCapacity(array $entry, int $quantity): int
    {
        $stats = is_array($entry['stats'] ?? null) ? $entry['stats'] : [];
        return max(0, $quantity) * max(0, (int) ($stats['fuelCapacity'] ?? 0));
    }

    /** @param array<string, mixed> $fleet */
    private function fuelShareForCapacity(array $fleet, int $movedCapacity): int
    {
        $capacity = max(0, (int) ($fleet['fuelCapacity'] ?? 0));
        $fuel = max(0, min($capacity, (int) ($fleet['fuel'] ?? $capacity)));
        if ($capacity <= 0 || $fuel <= 0 || $movedCapacity <= 0) {
            return 0;
        }

        return min($fuel, (int) round($fuel * min($capacity, $movedCapacity) / $capacity));
    }

    /** @param list<mixed> $fleets */
    private function countPlayerFleetsAtSystem(array $fleets, int $playerId, string $systemId): int
    {
        return count(array_filter(
            $fleets,
            static fn (mixed $fleet): bool => is_array($fleet)
                && (int) ($fleet['ownerPlayerId'] ?? 0) === $playerId
                && ($fleet['systemId'] ?? null) === $systemId,
        ));
    }

    /** @param list<mixed> $fleets */
    private function findFleetIndex(array $fleets, string $fleetId): ?int
    {
        foreach ($fleets as $index => $fleet) {
            if (is_array($fleet) && ($fleet['id'] ?? null) === $fleetId) {
                return $index;
            }
        }

        return null;
    }

    /** @param array<string, mixed> $system */
    private function findResourceIndex(array $system, string $resourceId): ?int
    {
        $resources = is_array($system['resources'] ?? null) ? $system['resources'] : [];
        foreach ($resources as $index => $resource) {
            if (is_array($resource) && ($resource['id'] ?? null) === $resourceId) {
                return $index;
            }
        }

        return null;
    }

    /** @return array<string, mixed>|null */
    private function productionDefinition(string $item, array $state, int $playerId, string $modelId = '', string $productionKind = '', string $sourceModelId = ''): ?array
    {
        $legacy = [
            'Scout Wing' => 'current_scout',
            'Defense Grid' => 'defense_grid_mk1',
            'Orbital Factory' => 'orbital_factory_mk1',
            'Deep Space Array' => 'deep_space_array_mk1',
        ];
        $requested = $modelId !== '' ? $modelId : ($legacy[$item] ?? $item);
        if ($requested === 'current_scout') {
            $design = TechnologyModelCatalog::currentDesign($state, $playerId);
            return [
                'kind' => 'ship', 'modelId' => (string) $design['id'], 'name' => (string) $design['name'],
                'version' => (int) ($design['generation'] ?? 1), 'cost' => max(1, (int) ($design['industryCost'] ?? 300)), 'design' => $design,
            ];
        }
        $design = TechnologyModelCatalog::resolveDesign($state, $playerId, $requested);
        if ($design !== null) {
            return [
                'kind' => 'ship', 'modelId' => (string) $design['id'], 'name' => (string) $design['name'],
                'version' => (int) ($design['generation'] ?? 1), 'cost' => max(1, (int) ($design['industryCost'] ?? 300)), 'design' => $design,
            ];
        }
        $model = TechnologyModelCatalog::model($requested);
        if ($model === null || ($model['category'] ?? null) !== 'installation') {
            return null;
        }
        $catalog = TechnologyModelCatalog::publicForPlayer($state, $playerId);
        $allowed = false;
        foreach ($catalog['installations'] as $candidate) {
            if (($candidate['id'] ?? null) === $requested && ($candidate['unlocked'] ?? false) === true) {
                $allowed = true;
                break;
            }
        }
        if (!$allowed) {
            return null;
        }
        if ($productionKind === 'upgrade') {
            $upgrade = TechnologyModelCatalog::installationUpgradeDefinition($state, $playerId, $sourceModelId, $requested);
            if ($upgrade === null) {
                return null;
            }
            $source = TechnologyModelCatalog::model($sourceModelId);
            return [
                'kind' => 'upgrade', 'modelId' => (string) $upgrade['id'], 'name' => sprintf('Upgrade to %s', (string) $upgrade['name']),
                'version' => (int) $upgrade['version'], 'cost' => max(1, (int) ($upgrade['upgradeCost'] ?? 0)), 'turns' => max(1, (int) ($upgrade['upgradeTurns'] ?? 1)),
                'sourceModelId' => $sourceModelId, 'sourceName' => (string) ($source['name'] ?? $sourceModelId), 'sourceVersion' => (int) ($source['version'] ?? 1), 'model' => $upgrade,
            ];
        }
        return [
            'kind' => 'installation', 'modelId' => (string) $model['id'], 'name' => (string) $model['name'],
            'version' => (int) $model['version'], 'cost' => max(1, (int) ($model['stats']['industryCost'] ?? 0)), 'model' => $model,
        ];
    }

    /**
     * Consume one component-backed colony ship when possible. Legacy starting
     * fleets keep the old single-use fleet-level module behavior.
     *
     * @param array<string, mixed> $fleet
     * @return array{fleet:array<string,mixed>|null,designName:string|null,shipConsumed:bool}
     */
    private function consumeColonyCapacity(array $fleet): array
    {
        $composition = is_array($fleet['composition'] ?? null) ? array_values($fleet['composition']) : [];
        foreach ($composition as $index => $entry) {
            if (!is_array($entry)) {
                continue;
            }
            $stats = is_array($entry['stats'] ?? null) ? $entry['stats'] : [];
            $perShip = max(0, (int) ($stats['colonizationCapacity'] ?? 0));
            $quantity = max(0, (int) ($entry['quantity'] ?? 0));
            if ($perShip < 1 || $quantity < 1) {
                continue;
            }

            $designName = is_string($entry['designName'] ?? null) ? $entry['designName'] : null;
            --$quantity;
            if ($quantity <= 0) {
                array_splice($composition, $index, 1);
            } else {
                $composition[$index]['quantity'] = $quantity;
            }

            $fleet['composition'] = array_values($composition);
            $fleet['ships'] = max(0, (int) ($fleet['ships'] ?? 0) - 1);
            $fleet['colonizationCapacity'] = max(0, $this->colonyCapacity($fleet) - $perShip);
            if ((int) $fleet['ships'] <= 0) {
                return ['fleet' => null, 'designName' => $designName, 'shipConsumed' => true];
            }

            return ['fleet' => $fleet, 'designName' => $designName, 'shipConsumed' => true];
        }

        $legacyCapacity = max(
            0,
            (int) ($fleet['legacyColonizationCapacity'] ?? $this->colonyCapacity($fleet)),
        );
        $fleet['legacyColonizationCapacity'] = max(0, $legacyCapacity - 1);
        $fleet['colonizationCapacity'] = max(0, $this->colonyCapacity($fleet) - 1);
        return ['fleet' => $fleet, 'designName' => null, 'shipConsumed' => false];
    }

    /** @param array<string, mixed> $fleet */
    private function colonyCapacity(array $fleet): int
    {
        if (isset($fleet['colonizationCapacity']) && is_numeric($fleet['colonizationCapacity'])) {
            return max(0, (int) $fleet['colonizationCapacity']);
        }

        if (isset($fleet['legacyColonizationCapacity']) && is_numeric($fleet['legacyColonizationCapacity'])) {
            return max(0, (int) $fleet['legacyColonizationCapacity']);
        }

        // Backwards compatibility for pre-dev6 starting test games.
        return ($fleet['role'] ?? null) === 'Exploration fleet' ? 1 : 0;
    }

    /** @param list<mixed> $routes */
    private function systemDistance(array $routes, string $a, string $b, int $maxDistance): ?int
    {
        if ($a === '' || $b === '') {
            return null;
        }
        if ($a === $b) {
            return 0;
        }

        $adjacency = [];
        foreach ($routes as $route) {
            if (!is_array($route)) {
                continue;
            }
            $from = is_string($route['from'] ?? null) ? $route['from'] : '';
            $to = is_string($route['to'] ?? null) ? $route['to'] : '';
            if ($from === '' || $to === '') {
                continue;
            }
            $adjacency[$from][] = $to;
            $adjacency[$to][] = $from;
        }

        $visited = [$a => true];
        $frontier = [$a];
        for ($distance = 1; $distance <= max(1, $maxDistance); ++$distance) {
            $next = [];
            foreach ($frontier as $systemId) {
                foreach ($adjacency[$systemId] ?? [] as $neighbourId) {
                    if (isset($visited[$neighbourId])) {
                        continue;
                    }
                    if ($neighbourId === $b) {
                        return $distance;
                    }
                    $visited[$neighbourId] = true;
                    $next[] = $neighbourId;
                }
            }
            if ($next === []) {
                break;
            }
            $frontier = $next;
        }

        return null;
    }
}
