framework:
  messenger:
    failure_transport: failed
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 5
          delay: 2000
          multiplier: 2
          max_delay: 60000
      failed:
        dsn: 'doctrine://default?queue_name=failed'
    routing:
      Bellcom\StarsTurnBundle\Message\GenerateTurnMessage: async
      Bellcom\StarsTurnBundle\Message\SendNotificationMessage: async
